### ISSUE TITLE
`node-role.kubernetes.io/master` is no longer supported

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/node-manager#119]
https://github.com/h3poteto/node-manager/blob/43b3aa517d66cb2bafd9002977f35b451ab08002/pkg/controllers/nodemanager/controller.go#L40

Here are master node labels
```yaml
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: t3.small
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: ap-northeast-1
    failure-domain.beta.kubernetes.io/zone: ap-northeast-1c
    kops.k8s.io/instancegroup: master-ap-northeast-1c
    kops.k8s.io/kops-controller-pki: ""
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: i-0a586788b14a04426
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/spot-worker: "true"
    node.kubernetes.io/exclude-from-external-load-balancers: ""
    node.kubernetes.io/instance-type: t3.small
    topology.ebs.csi.aws.com/zone: ap-northeast-1c
    topology.kubernetes.io/region: ap-northeast-1
    topology.kubernetes.io/zone: ap-northeast-1c
```

Here are worker node labels
```yaml
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: t3.medium
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: ap-northeast-1
    failure-domain.beta.kubernetes.io/zone: ap-northeast-1c
    kops.k8s.io/instancegroup: nodes-ap-northeast-1c
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: i-0fa1ea25215a3ce28
    kubernetes.io/os: linux
    node-role.kubernetes.io/node: ""
    node-role.kubernetes.io/spot-worker: "true"
    node.kubernetes.io/instance-type: t3.medium
    topology.ebs.csi.aws.com/zone: ap-northeast-1c
    topology.kubernetes.io/region: ap-northeast-1
    topology.kubernetes.io/zone: ap-northeast-1c
```
