### ISSUE TITLE
Could not craete master and worker config at the same time

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/node-manager#35]
When I provide these configuration, node-manager created only master resources.

```yaml
        spec:
          aws:
            region: ap-northeast-1
            masters:
              desired: 3
              asgModifyCoolTimeSeconds: 600
              refreshSchedule: "00 15 * * 6"
              enableReplenish: true
              autoScalingGroups:
                - name: master-ap-northeast-1a.masters.external-prd-20210225.k8s.h3poteto.dev
                - name: master-ap-northeast-1c.masters.external-prd-20210225.k8s.h3poteto.dev
                - name: master-ap-northeast-1d.masters.external-prd-20210225.k8s.h3poteto.dev
            workers:
              desired: 3
              asgModifyCoolTimeSeconds: 600
              refreshSchedule: "00 15 * * 5"
              enableReplenish: true
              autoScalingGroups:
                - name: nodes-ap-northeast-1a.external-prd-20210225.k8s.h3poteto.dev
                - name: nodes-ap-northeast-1c.external-prd-20210225.k8s.h3poteto.dev
                - name: nodes-ap-northeast-1d.external-prd-20210225.k8s.h3poteto.dev
```
